# Generated by Django 6.0.7 on 2026-07-11 10:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationAuto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('vin_valide', models.BooleanField(default=False, verbose_name='VIN valide')),
                ('assurance_valide', models.BooleanField(default=False, verbose_name='Assurance valide')),
                ('ct_valide', models.BooleanField(default=False, verbose_name='Contrôle technique valide')),
                ('doublon_detecte', models.BooleanField(default=False, verbose_name='Doublon détecté')),
                ('score_fraude', models.PositiveSmallIntegerField(default=0, verbose_name='Score de fraude (0-100)')),
                ('niveau_risque', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé')], default='FAIBLE', max_length=8, verbose_name='Niveau de risque')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détail des contrôles')),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='dossiers.dossier', verbose_name='Dossier')),
                ('dossier_doublon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doublons_signales', to='dossiers.dossier', verbose_name='Dossier en doublon')),
            ],
            options={
                'verbose_name': 'Vérification automatique',
                'verbose_name_plural': 'Vérifications automatiques',
                'ordering': ['-date_maj'],
            },
        ),
    ]
