# Generated by Django 6.0.7 on 2026-07-11 11:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('donnees_snapshot', models.JSONField(default=dict, verbose_name='Données figées')),
                ('hash_sha256', models.CharField(max_length=64, verbose_name='Empreinte SHA-256')),
                ('signature_rsa', models.TextField(verbose_name='Signature RSA (base64)')),
                ('qr_payload', models.TextField(verbose_name='Contenu du QR')),
                ('pdf_fichier', models.FileField(blank=True, upload_to='certificats/', verbose_name='Certificat PDF')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('REVOQUE', 'Révoqué'), ('EXPIRE', 'Expiré')], db_index=True, default='ACTIF', max_length=10, verbose_name='Statut')),
                ('date_emission', models.DateTimeField(verbose_name='Émis le')),
                ('date_expiration', models.DateTimeField(verbose_name='Expire le')),
                ('motif_revocation', models.TextField(blank=True, default='', verbose_name='Motif de révocation')),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificat', to='dossiers.dossier', verbose_name='Dossier')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='dossiers.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
                'ordering': ['-date_emission'],
            },
        ),
    ]
