# Generated by Django 6.0.7 on 2026-07-11 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid_scanne', models.UUIDField(db_index=True, verbose_name='UUID scanné')),
                ('resultat', models.CharField(choices=[('AUTHENTIQUE', 'Authentique'), ('FALSIFIE', 'Falsifié'), ('REVOQUE', 'Révoqué'), ('EXPIRE', 'Expiré'), ('INTROUVABLE', 'Introuvable')], max_length=12, verbose_name='Résultat')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('localisation', models.CharField(blank=True, default='', max_length=120, verbose_name='Localisation')),
                ('date_scan', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Scanné le')),
                ('certificat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='certificats.certificat', verbose_name='Certificat')),
                ('scanne_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to=settings.AUTH_USER_MODEL, verbose_name='Scanné par')),
            ],
            options={
                'verbose_name': 'Scan de vérification',
                'verbose_name_plural': 'Scans de vérification',
                'ordering': ['-date_scan'],
            },
        ),
    ]
