# Generated by Django 6.0.7 on 2026-07-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificats', '0002_scanlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='methode',
            field=models.CharField(choices=[('QR', 'QR'), ('PLAQUE', 'Immatriculation')], default='QR', max_length=8, verbose_name='Méthode'),
        ),
    ]
