# Generated by Django 6.0.7 on 2026-07-11 10:14

import apps.accounts.managers
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse e-mail')),
                ('telephone', models.CharField(help_text='Format international, ex : +22370000000', max_length=20, unique=True, verbose_name='Téléphone')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('role', models.CharField(choices=[('USAGER', 'Usager'), ('AGENT', 'Agent validateur'), ('FORCE_ORDRE', "Force de l'ordre"), ('ADMIN', 'Administrateur')], default='USAGER', max_length=16, verbose_name='Rôle')),
                ('is_email_verifie', models.BooleanField(default=False, verbose_name='E-mail vérifié')),
                ('is_telephone_verifie', models.BooleanField(default=False, verbose_name='Téléphone vérifié')),
                ('is_active', models.BooleanField(default=False, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Accès admin Django')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_creation'],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canal', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'E-mail')], max_length=8)),
                ('code_hash', models.CharField(max_length=128)),
                ('tentatives', models.PositiveSmallIntegerField(default=0)),
                ('consomme', models.BooleanField(default=False)),
                ('expire_le', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_otp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code OTP',
                'verbose_name_plural': 'Codes OTP',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['user', 'consomme'], name='accounts_ot_user_id_d25aae_idx')],
            },
        ),
    ]
