# Generated by Django 6.0.7 on 2026-07-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(help_text='Format international, ex : +245955123456', max_length=20, unique=True, verbose_name='Téléphone'),
        ),
    ]
