# Generated by Django 6.0.7 on 2026-07-11 10:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('DEMANDE_COMPLEMENT', 'Demande de complément')], max_length=20, verbose_name='Action')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire / motif')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': "Décision d'agent",
                'verbose_name_plural': 'Historique des décisions',
                'ordering': ['-date_creation'],
            },
        ),
    ]
