# Generated by Django 6.0.7 on 2026-07-11 16:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('VOLE', 'Véhicule volé'), ('RECHERCHE', 'Véhicule recherché'), ('OPPOSITION', 'Opposition administrative')], default='VOLE', max_length=12, verbose_name='Type')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('LEVE', 'Levé')], db_index=True, default='ACTIF', max_length=8, verbose_name='Statut')),
                ('reference', models.CharField(blank=True, default='', max_length=60, verbose_name='Référence (PV / dossier)')),
                ('motif', models.TextField(blank=True, default='', verbose_name='Motif / circonstances')),
                ('date_signalement', models.DateTimeField(auto_now_add=True, verbose_name='Signalé le')),
                ('date_levee', models.DateTimeField(blank=True, null=True, verbose_name='Levé le')),
                ('motif_levee', models.CharField(blank=True, default='', max_length=200, verbose_name='Motif de levée')),
                ('leve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_leves', to=settings.AUTH_USER_MODEL, verbose_name='Levé par')),
                ('signale_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_emis', to=settings.AUTH_USER_MODEL, verbose_name='Signalé par')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='dossiers.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-date_signalement'],
                'indexes': [models.Index(fields=['vehicule', 'statut'], name='signalement_vehicul_4687e5_idx')],
            },
        ),
    ]
