# Generated by Django 5.2.11 on 2026-07-13 19:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationPaiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('devise', models.CharField(default='XOF', max_length=8, verbose_name='Devise')),
                ('montant_taxe', models.PositiveIntegerField(default=15000, verbose_name="Taxe d'immatriculation")),
                ('montant_timbre', models.PositiveIntegerField(default=2000, verbose_name='Timbre fiscal')),
                ('frais_service', models.PositiveIntegerField(default=500, verbose_name='Frais de service')),
                ('paiement_requis', models.BooleanField(default=False, help_text="Si activé, le certificat ne peut être émis qu'après règlement de la taxe.", verbose_name='Paiement requis avant le certificat')),
            ],
            options={
                'verbose_name': 'Configuration des paiements',
                'verbose_name_plural': 'Configuration des paiements',
            },
        ),
        migrations.CreateModel(
            name='OperateurPaiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=40, verbose_name='Nom')),
                ('code', models.CharField(help_text='Ex. ORANGE, MTN', max_length=20, verbose_name='Code court')),
                ('code_ussd', models.CharField(blank=True, default='', max_length=20, verbose_name='Code USSD')),
                ('couleur', models.CharField(default='#0d2748', max_length=9, verbose_name='Couleur (hex)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Opérateur de paiement',
                'verbose_name_plural': 'Opérateurs de paiement',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=24, unique=True, verbose_name='Référence du reçu')),
                ('devise', models.CharField(default='XOF', max_length=8, verbose_name='Devise')),
                ('montant_total', models.PositiveIntegerField(verbose_name='Montant total')),
                ('detail', models.JSONField(default=list, verbose_name='Détail (lignes)')),
                ('operateur', models.CharField(max_length=40, verbose_name='Opérateur')),
                ('code_ussd', models.CharField(blank=True, default='', max_length=20, verbose_name='Code USSD')),
                ('numero_telephone', models.CharField(max_length=24, verbose_name='Numéro mobile money')),
                ('reference_transaction', models.CharField(blank=True, default='', max_length=40, verbose_name='Réf. transaction opérateur')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('ECHOUE', 'Échoué')], db_index=True, default='EN_ATTENTE', max_length=12, verbose_name='Statut')),
                ('paye_le', models.DateTimeField(blank=True, null=True, verbose_name='Payé le')),
                ('pdf_fichier', models.FileField(blank=True, null=True, upload_to='recus/', verbose_name='Reçu PDF')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='dossiers.dossier', verbose_name='Dossier')),
                ('initie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_inities', to=settings.AUTH_USER_MODEL, verbose_name='Initié par')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['dossier', 'statut'], name='paiements_p_dossier_ec0a14_idx')],
            },
        ),
    ]
