# Generated by Django 5.2.11 on 2026-07-13 22:27

from django.db import migrations, models


def exiger_paiement(apps, schema_editor):
    """Active l'exigence de paiement sur la configuration existante (créée à False)."""
    Config = apps.get_model("paiements", "ConfigurationPaiement")
    Config.objects.update(paiement_requis=True)


def annuler(apps, schema_editor):
    Config = apps.get_model("paiements", "ConfigurationPaiement")
    Config.objects.update(paiement_requis=False)


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_operateurs_defaut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationpaiement',
            name='paiement_requis',
            field=models.BooleanField(default=True, help_text="Si activé, le certificat n'est délivré (et téléchargeable) qu'après règlement de la taxe.", verbose_name='Paiement requis avant le certificat'),
        ),
        migrations.RunPython(exiger_paiement, annuler),
    ]
