# Generated by Django 6.0.7 on 2026-07-11 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=64, verbose_name='Action')),
                ('objet_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('objet_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'action",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['action', 'date'], name='core_logact_action_77a667_idx'), models.Index(fields=['objet_type', 'objet_id'], name='core_logact_objet_t_738103_idx')],
            },
        ),
    ]
