# Generated by Django 5.2.11 on 2026-07-13 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeInfraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=80, verbose_name='Libellé')),
                ('code', models.CharField(help_text='Ex. EXCES_VITESSE', max_length=32, unique=True, verbose_name='Code court')),
                ('montant', models.PositiveIntegerField(verbose_name="Montant de l'amende")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Type d'infraction",
                'verbose_name_plural': 'Barème des infractions',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=24, unique=True, verbose_name='Référence du PV')),
                ('libelle', models.CharField(max_length=80, verbose_name='Infraction')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant')),
                ('devise', models.CharField(default='XOF', max_length=8, verbose_name='Devise')),
                ('lieu', models.CharField(blank=True, default='', max_length=160, verbose_name='Lieu du contrôle')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observations')),
                ('date_infraction', models.DateTimeField(verbose_name='Constatée le')),
                ('statut', models.CharField(choices=[('A_REGLER', 'À régler'), ('PAYEE', 'Soldée'), ('CONTESTEE', 'Contestée'), ('ANNULEE', 'Annulée')], db_index=True, default='A_REGLER', max_length=12, verbose_name='Statut')),
                ('motif_contestation', models.TextField(blank=True, default='', verbose_name='Motif de contestation')),
                ('motif_annulation', models.TextField(blank=True, default='', verbose_name="Motif d'annulation")),
                ('operateur', models.CharField(blank=True, default='', max_length=40, verbose_name='Opérateur')),
                ('code_ussd', models.CharField(blank=True, default='', max_length=20, verbose_name='Code USSD')),
                ('numero_telephone', models.CharField(blank=True, default='', max_length=24, verbose_name='Numéro mobile money')),
                ('reference_transaction', models.CharField(blank=True, default='', max_length=40, verbose_name='Réf. transaction')),
                ('quittance_reference', models.CharField(blank=True, default='', max_length=24, verbose_name='Référence quittance')),
                ('paye_le', models.DateTimeField(blank=True, null=True, verbose_name='Réglée le')),
                ('quittance_fichier', models.FileField(blank=True, null=True, upload_to='quittances/', verbose_name='Quittance PDF')),
                ('dressee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infractions_dressees', to=settings.AUTH_USER_MODEL, verbose_name='Agent verbalisateur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infractions', to='dossiers.vehicule', verbose_name='Véhicule')),
                ('type_infraction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infractions', to='infractions.typeinfraction', verbose_name="Type d'infraction")),
            ],
            options={
                'verbose_name': 'Infraction',
                'verbose_name_plural': 'Infractions',
                'ordering': ['-date_infraction'],
                'indexes': [models.Index(fields=['vehicule', 'statut'], name='infractions_vehicul_c17156_idx')],
            },
        ),
    ]
