# Generated by Django 6.0.7 on 2026-07-11 11:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Immatriculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(editable=False, max_length=16, unique=True, verbose_name="Numéro d'immatriculation")),
                ('serie_plaque', models.CharField(editable=False, max_length=4, verbose_name='Série')),
                ('sequence', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Rang séquentiel')),
                ('date_attribution', models.DateTimeField(auto_now_add=True, verbose_name='Attribuée le')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immatriculations_attribuees', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('vehicule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='immatriculation', to='dossiers.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Immatriculation',
                'verbose_name_plural': 'Immatriculations',
                'ordering': ['-sequence'],
            },
        ),
    ]
