# Generated by Django 5.2.11 on 2026-07-13 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
        ('immatriculations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='immatriculation',
            options={'ordering': ['-date_attribution'], 'verbose_name': 'Immatriculation', 'verbose_name_plural': 'Immatriculations'},
        ),
        migrations.AddField(
            model_name='immatriculation',
            name='categorie',
            field=models.CharField(choices=[('STANDARD', 'Standard (voiture, utilitaire…)'), ('MOTO', 'Moto / tricycle')], default='STANDARD', editable=False, max_length=12, verbose_name='Catégorie de plaque'),
        ),
        migrations.AlterField(
            model_name='immatriculation',
            name='sequence',
            field=models.PositiveIntegerField(editable=False, verbose_name='Rang séquentiel'),
        ),
        migrations.AddConstraint(
            model_name='immatriculation',
            constraint=models.UniqueConstraint(fields=('categorie', 'sequence'), name='immat_sequence_unique_par_categorie'),
        ),
    ]
