# Generated by Django 6.0.7 on 2026-07-11 10:38

import apps.dossiers.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('numero_dossier', models.CharField(editable=False, max_length=24, unique=True, verbose_name='N° de dossier')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('VERIF_AUTO', 'Vérification automatique'), ('EN_VALIDATION', 'En validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('IMMATRICULE', 'Immatriculé'), ('CERTIFIE', 'Certifié'), ('ARCHIVE', 'Archivé')], db_index=True, default='BROUILLON', max_length=16, verbose_name='Statut')),
                ('motif_rejet', models.TextField(blank=True, default='', verbose_name='Motif de rejet')),
                ('date_soumission', models.DateTimeField(blank=True, null=True, verbose_name='Soumis le')),
                ('agent_assigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Agent assigné')),
                ('usager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to=settings.AUTH_USER_MODEL, verbose_name='Usager')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('type_document', models.CharField(choices=[('CNI', "Pièce d'identité"), ('CARTE_GRISE', 'Carte grise'), ('ASSURANCE', "Attestation d'assurance"), ('CONTROLE_TECHNIQUE', 'Contrôle technique'), ('FACTURE', "Facture d'achat"), ('AUTRE', 'Autre pièce')], max_length=20, verbose_name='Type')),
                ('fichier', models.FileField(upload_to=apps.dossiers.models.chemin_document, verbose_name='Fichier')),
                ('format', models.CharField(blank=True, default='', max_length=8, verbose_name='Format')),
                ('taille', models.PositiveIntegerField(default=0, verbose_name='Taille (octets)')),
                ('hash_fichier', models.CharField(blank=True, default='', max_length=64, verbose_name='Empreinte SHA-256')),
                ('ocr_texte', models.TextField(blank=True, default='', verbose_name='Texte OCR')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name="Date de début / d'émission")),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name="Date de fin / d'échéance")),
                ('statut_verif', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFORME', 'Conforme'), ('NON_CONFORME', 'Non conforme')], default='EN_ATTENTE', max_length=14, verbose_name='Statut de vérification')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['type_document'],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('vin', models.CharField(db_index=True, max_length=17, verbose_name='Numéro de châssis (VIN)')),
                ('marque', models.CharField(max_length=60, verbose_name='Marque')),
                ('modele', models.CharField(max_length=60, verbose_name='Modèle')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('couleur', models.CharField(blank=True, default='', max_length=40, verbose_name='Couleur')),
                ('energie', models.CharField(choices=[('ESSENCE', 'Essence'), ('DIESEL', 'Diesel'), ('ELECTRIQUE', 'Électrique'), ('HYBRIDE', 'Hybride'), ('GPL', 'GPL')], max_length=12, verbose_name='Énergie')),
                ('type_vehicule', models.CharField(choices=[('VP', 'Voiture particulière'), ('UTILITAIRE', 'Utilitaire'), ('MOTO', 'Moto / tricycle'), ('POIDS_LOURD', 'Poids lourd'), ('BUS', 'Bus / transport en commun')], max_length=12, verbose_name='Type')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='dossier',
            name='vehicule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='dossiers.vehicule', verbose_name='Véhicule'),
        ),
    ]
