# Generated by Django 5.2.11 on 2026-07-13 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='motif_verif',
            field=models.TextField(blank=True, default='', verbose_name='Motif (si non conforme)'),
        ),
        migrations.AddField(
            model_name='document',
            name='verifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_verifies', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par'),
        ),
    ]
