# Generated by Django 5.2.11 on 2026-07-13 23:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpsControle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=80, verbose_name='Nom')),
                ('nom_court', models.CharField(blank=True, default='', max_length=40, verbose_name='Nom court')),
                ('code', models.CharField(help_text='Ex. CIRCULATION, GARDE_NAT', max_length=24, unique=True, verbose_name='Code')),
                ('sigle', models.CharField(help_text='Badge court, ex. PT, GN', max_length=4, verbose_name='Sigle')),
                ('couleur', models.CharField(default='#0d2748', max_length=9, verbose_name='Couleur (hex)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Corps de contrôle',
                'verbose_name_plural': 'Corps de contrôle',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='DemandeHabilitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=24, unique=True, verbose_name='Référence')),
                ('matricule', models.CharField(max_length=40, verbose_name='Matricule / N° de service')),
                ('grade', models.CharField(blank=True, default='', max_length=60, verbose_name='Grade')),
                ('unite', models.CharField(blank=True, default='', max_length=100, verbose_name='Unité / Brigade')),
                ('region', models.CharField(blank=True, default='', max_length=60, verbose_name='Région')),
                ('justificatif', models.FileField(help_text='Carte professionnelle ou ordre de mission.', upload_to='habilitations/', verbose_name='Pièce justificative')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validée'), ('REJETE', 'Rejetée')], db_index=True, default='EN_ATTENTE', max_length=12, verbose_name='Statut')),
                ('motif_decision', models.TextField(blank=True, default='', verbose_name='Motif de la décision')),
                ('decide_le', models.DateTimeField(blank=True, null=True, verbose_name='Décidée le')),
                ('corps', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='habilitations.corpscontrole', verbose_name='Corps')),
                ('decide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habilitations_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Décidée par')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habilitation', to=settings.AUTH_USER_MODEL, verbose_name='Compte')),
            ],
            options={
                'verbose_name': "Demande d'habilitation",
                'verbose_name_plural': "Demandes d'habilitation",
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['statut', 'date_creation'], name='habilitatio_statut_c68ceb_idx')],
            },
        ),
    ]
