# Generated by Django 5.2.11 on 2026-07-13 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferencesNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('canal_email', models.BooleanField(default=True, verbose_name='E-mail')),
                ('canal_sms', models.BooleanField(default=True, verbose_name='SMS')),
                ('canal_push', models.BooleanField(default=False, verbose_name='Notifications push')),
                ('delais_relance', models.JSONField(default=list, verbose_name='Délais de relance (jours)')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_notification', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférences de notification',
                'verbose_name_plural': 'Préférences de notification',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('niveau', models.CharField(choices=[('SUCCES', 'Succès'), ('INFO', 'Information'), ('ALERTE', 'Alerte'), ('ACTION', 'Action requise'), ('NEUTRE', 'Neutre')], default='NEUTRE', max_length=8, verbose_name='Niveau')),
                ('categorie', models.CharField(blank=True, default='', max_length=40, verbose_name='Catégorie')),
                ('titre', models.CharField(max_length=140, verbose_name='Titre')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message')),
                ('lien', models.CharField(blank=True, default='', max_length=200, verbose_name='Lien (route front)')),
                ('cta_label', models.CharField(blank=True, default='', max_length=60, verbose_name='Libellé du bouton')),
                ('cle_unicite', models.CharField(blank=True, db_index=True, default='', max_length=160, verbose_name="Clé d'unicité")),
                ('lu', models.BooleanField(db_index=True, default=False, verbose_name='Lu')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['destinataire', 'lu'], name='notificatio_destina_353850_idx')],
            },
        ),
    ]
